### ISSUE TITLE
What's the difference between `logical` and `physical` test?

### ISSUE THREAD

**Issue by leiysky** [risinglightdb/sqlplannertest-rs#1]

**Comment by xxchan** [comment]
They are user-defined `tasks` 😄

When implementing the trait, the user defines how to hanle tasks, and the result is stored AS-IS in `*.sql`

```rust
impl sqlplannertest::PlannerTestRunner for NaiveDb {
    async fn run(&mut self, test_case: &sqlplannertest::ParsedTestCase) -> Result<String> {
        ...
		for task in &test_case.tasks {
            writeln!(r, "=== {}", task)?;
            writeln!(r, "I'm a naive db, so I don't now how to process")?;
            for before in &test_case.before_sql {
                writeln!(r, "{}", before)?;
            }
            writeln!(r, "{}", test_case.sql)?;
            writeln!(r)?;
        }
	}
}
```

```yaml
- sql: |
    SELECT * FROM t1, t2 WHERE t1.v1 = t2.v2;
  desc: Test whether join works correctly.
  before: ["*sql1", "*sql2", "CREATE TABLE t3(v3 int);"]
  tasks:
  - logical
  - physical
```

becomes

```sql
-- Test whether join works correctly.
SELECT * FROM t1, t2 WHERE t1.v1 = t2.v2;

/*
=== logical
I'm a naive db, so I don't now how to process
CREATE TABLE t1(v1 int);

CREATE TABLE t2(v2 int);

CREATE TABLE t3(v3 int);
SELECT * FROM t1, t2 WHERE t1.v1 = t2.v2;


=== physical
I'm a naive db, so I don't now how to process
CREATE TABLE t1(v1 int);

CREATE TABLE t2(v2 int);

CREATE TABLE t3(v3 int);
SELECT * FROM t1, t2 WHERE t1.v1 = t2.v2;
*/


```
